name: nextcloud-bare

services:

  web:
    image: nginx
    container_name: nextcloud_webserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    ports:
      - 80:80
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST={DOMAIN}
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=nginx
      - LETSENCRYPT_HOST={DOMAIN}
      - LETSENCRYPT_EMAIL={DOMAIN@EMAIL}
    networks:
      - nextcloud-fpm
    restart: always

  app:
    image: nextcloud:fpm
    container_name: nextcloud_fpm
    links:
      - db
    volumes:
      - /Servers/lshowers-share/nextcloud_apps:/var/www/html/apps
      - /configs/nextcloud/config:/var/www/html/config
      - /Servers/lshowers-share:/var/www/html/data
    networks:
      - nextcloud-fpm
    restart: always
    
  db:
    image: mariadb
    container_name: db
    volumes:
      - /configs/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=SUPERSECRETPASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    networks:
      - nextcloud-fpm
    restart: always

networks:
  nextcloud-fpm:
    external:
      name: nginx
